# Generated by Django 4.1.2 on 2022-10-28 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_contact_timestamp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="name",
        ),
    ]
