# Generated by Django 4.1.2 on 2022-10-28 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_remove_contact_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="name",
            field=models.CharField(default=1, max_length=225),
            preserve_default=False,
        ),
    ]
